FROM python:3.9-slim-bullseye

RUN pip install pipenv

WORKDIR /app
COPY ["Pipfile", "Pipfile.lock", "predict.py", "xgb_model.pkl", "./"]

RUN pipenv install --system --deploy

EXPOSE 9696

ENTRYPOINT [ "waitress-serve", "--host=0.0.0.0", "--port=9696", "predict:app" ]
